backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "noticias"
    label: "Noticias"
    files:
      - file: "noticias/lista.json"
        label: "Lista de Noticias"
        name: "lista"
        fields:
          - {label: "Título", name: "titulo", widget: "string"}
          - {label: "Fecha", name: "fecha", widget: "datetime"}
          - {label: "Imagen", name: "imagen", widget: "string"}
          - {label: "Resumen", name: "resumen", widget: "text"}
          - {label: "URL", name: "url", widget: "string"}